### ISSUE TITLE
Mac: cannot ping docker

### ISSUE THREAD

**Issue by aistis-** [iamluc/docker-hostmanager#35]
Hello, I have tried using the manager on mac - it works as expected. The IP is resolved correctly, but `ping custom.address` give a timeout - I cannot ping the container. Do you have any ideas what could be the reason. I am using a native Docker for Mac.

**Comment by spyro1st** [comment]
Hi,

i also try to use it with native Docker for Mac. Is this even possible? If i understand correctly the access to the containers does no work:

https://docs.docker.com/docker-for-mac/networking/

Did you figure it out? Or do you have to use a "normal" virtual machine with Docker running instead of native Docker for Mac implementation?

**Comment by aistis-** [comment]
@km-digitalpatrioten I figured out the same as you :( does not seem possible to make it work with Mac at the moment.
Off-topic: I have faced another problem, that applications which has lot of files, are working veeeery slow on mac + native docker because of slow file sync.

**Comment by spyro1st** [comment]
Thanks for your reply. Did you tried it with a VMware machine instead? The performance of this FS sync seems to be quite good.

**Comment by aistis-** [comment]
@km-digitalpatrioten it should solve file sync issue or at least increase the performance, but I did not try actually as some problems comes with VM approach.

**Comment by spyro1st** [comment]
Thanks again. I think i'll continue with our current vagrant + docker stack and wait for future development regarding the network implementation on Mac.
